--- 
apiVersion: v1
kind: Pod
metadata: 
  labels: 
    product-group: ui
spec: 
  containers: 
    - 
      etcHosts: 
        - 
          hostname: tfs.assurant.com
          ip: "172.20.0.42"
      image: "jenkinsci/jnlp-slave:alpine"
      name: jnlp
      securityContext: 
        allowPrivilegeEscalation: false
      tty: true
    - 
      command: 
        - /busybox/cat
      env: 
        - 
          name: DOCKER_CONFIG
          value: /kaniko/.docker
      image: "gcr.io/kaniko-project/executor:debug"
      name: docker-builder
      tty: true
      volumeMounts: 
        - 
          mountPath: /kaniko/.docker
          name: docker-config
    - 
      command: 
        - cat
      image: "sahsu/docker-jsonlint:latest"
      name: json-lint
      tty: true
  volumes: 
    - 
      name: docker-config
      secret: 
        items: 
          - 
            key: configjson
            path: config.json
        secretName: ui-registry-acr-login
